package com.finagent.report;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Parse-back verification of the PDF renderer (no Spring, no I/O, no network):
 * every assertion reads actual extracted text / page counts from generated bytes.
 */
class PdfReportGeneratorTest {

    private final PdfReportGenerator generator = new PdfReportGenerator();

    static ResearchReportData.Entry fullEntry(String symbol) {
        return new ResearchReportData.Entry(
                symbol, symbol + " Corp.", "150.25", "2.50", "1.69",
                "Technology", "2500000000000", "28.5",
                21, 12,
                List.of(symbol + " beats earnings expectations", symbol + " raises guidance"),
                "42.5", "MODERATE", "0.21", "0.045", "1.15", null,
                "available", "POSITIVE", "0.6", "0.8",
                "Market downturn weighs on sentiment",
                12, 12, 7, 3, 2,
                "lexicon-v1: per-article (pos-neg)/(pos+neg)",
                List.of());
    }

    static ResearchReportData report(UUID id, List<ResearchReportData.Entry> entries,
                                     String interpretation, String executiveSummary) {
        return report(id, entries, interpretation, executiveSummary,
                "AAPL (2 headlines, latest: beats earnings)");
    }

    static ResearchReportData report(UUID id, List<ResearchReportData.Entry> entries,
                                     String interpretation, String executiveSummary,
                                     String newsSummary) {
        return new ResearchReportData(
                id,
                "Analyze " + String.join(", ", entries.stream().map(ResearchReportData.Entry::symbol).toList()),
                Instant.parse("2026-09-04T10:00:00Z"),
                Instant.parse("2026-09-04T10:05:00Z"),
                entries.stream().map(ResearchReportData.Entry::symbol).toList(),
                executiveSummary,
                interpretation,
                newsSummary,
                "Educational research only, not financial advice.",
                0,
                entries);
    }

    private static String textOf(byte[] pdf) throws Exception {
        try (PDDocument document = Loader.loadPDF(pdf)) {
            return new PDFTextStripper().getText(document);
        }
    }

    private static int pagesOf(byte[] pdf) throws Exception {
        try (PDDocument document = Loader.loadPDF(pdf)) {
            return document.getPages().getCount();
        }
    }

    @Test
    void bundledUnicodeFontsLoad() throws Exception {
        // Phase 17: DejaVu TTFs are bundled (test classpath == main resources).
        // If this ever falls back, Unicode coverage is lost — fail loudly.
        try (PDDocument document = new PDDocument()) {
            assertThat(PdfReportGenerator.loadFonts(document).unicode()).isTrue();
        }
    }

    @Test
    void unicodeHeadlinesRenderVerbatim() throws Exception {
        // Phase 17: CJK, Devanagari, currency symbols and punctuation that the
        // old WinAnsi path degraded to '?'.
        ResearchReportData.Entry entry = new ResearchReportData.Entry(
                "TATAMOTORS", "Tata Motors \u0932\u093f\u092e\u093f\u091f\u0947\u0921",
                "987.65", "12.30", "1.26",
                "Auto", "35000000000", "18.2",
                21, 12,
                List.of("\u4e2d\u56fd\u7535\u52a8\u8f66\u9700\u6c42\u56de\u5347 — Tata \u20b9 target \u20ac outlook",
                        "Caf\u00e9 na\u00efve fa\u00e7ade — \u201cSonder-Edition\u201d \u2192 \u0394 growth"),
                "42.5", "MODERATE", "0.21", "0.045", "1.15", null,
                "available", "POSITIVE", "0.6", "0.8",
                "Market sentiment mixed",
                12, 12, 7, 3, 2,
                "lexicon-v1",
                List.of());
        byte[] pdf = generator.generate(report(UUID.randomUUID(), List.of(entry),
                "Interpretation with \u00a5 and \u00a3 figures.", "Summary with \u20b9."));

        String text = textOf(pdf);
        assertThat(text).contains("\u4e2d\u56fd").contains("\u20b9").contains("\u20ac");
        assertThat(text).contains("Caf\u00e9").contains("\u201cSonder-Edition\u201d");
        assertThat(text).doesNotContain("?");
    }

    @Test
    void hostileContentCannotBreakGeneration() throws Exception {
        // Phase 17: key-like material, paths, markup, control chars and a long
        // unbroken token must render (as inert text) without exceptions, hangs
        // or page-count explosion. UUID filenames stay server-derived (controller).
        String nasty = "sk-test-FAKEKEY " + "eyJhbGciOiJIUzI1NiJ9.FAKE.JWT "
                + "/etc/passwd C:\\Windows\\secret ${jndi:ldap://evil} <script>alert(1)</script> "
                + "line1\u0000\u0007line2 " + "x".repeat(500);
        ResearchReportData.Entry entry = new ResearchReportData.Entry(
                "AAPL", nasty, "150.25", null, null,
                null, null, null,
                0, 0,
                List.of(nasty, nasty),
                null, null, null, null, null, null,
                "unavailable", null, null, null,
                null, 0, 0, 0, 0, 0, null,
                List.of(nasty));
        long started = System.currentTimeMillis();
        byte[] pdf = generator.generate(report(UUID.randomUUID(), List.of(entry), nasty, nasty));
        assertThat(System.currentTimeMillis() - started).isLessThan(30_000);

        String text = textOf(pdf);
        assertThat(text).contains("AAPL");
        assertThat(pagesOf(pdf)).isLessThan(50);
    }

    @Test
    void completedReportRendersAllSections() throws Exception {
        UUID id = UUID.randomUUID();
        byte[] pdf = generator.generate(report(id, List.of(fullEntry("AAPL")),
                "Steady outlook with moderate risk.", "AAPL looks steady."));

        assertThat(pdf).isNotEmpty();
        assertThat(new String(pdf, 0, 4, java.nio.charset.StandardCharsets.US_ASCII)).isEqualTo("%PDF");
        String text = textOf(pdf);
        assertThat(text).contains("FINAGENT");
        assertThat(text).contains("Research Report");
        assertThat(text).contains(id.toString());
        assertThat(text).contains("AAPL");
        assertThat(text).contains("EXECUTIVE SUMMARY");
        assertThat(text).contains("AAPL looks steady.");
        assertThat(text).contains("150.25");
        assertThat(text).contains("Technology");
        assertThat(text).contains("Risk Analysis");
        assertThat(text).contains("MODERATE");
        assertThat(text).contains("NEWS & SENTIMENT");
        assertThat(text).contains("POSITIVE");
        assertThat(text).contains("lexicon-v1");
        assertThat(text).contains("AI INTERPRETATION");
        assertThat(text).contains("Steady outlook with moderate risk.");
        assertThat(text).contains("DISCLAIMER");
        assertThat(text).contains("Educational research only");
        assertThat(text).contains("Page 1");
    }

    @Test
    void multiStockReportListsEveryTicker() throws Exception {
        byte[] pdf = generator.generate(report(UUID.randomUUID(),
                List.of(fullEntry("TCS"), fullEntry("INFY"), fullEntry("RELIANCE"), fullEntry("HDFCBANK")),
                "Coverage across four names.", "Four-stock review."));

        String text = textOf(pdf);
        assertThat(text).contains("TCS").contains("INFY").contains("RELIANCE").contains("HDFCBANK");
        assertThat(pagesOf(pdf)).isGreaterThanOrEqualTo(1);
    }

    @Test
    void missingDataRendersUnavailableNeverFabricated() throws Exception {
        // Company known, everything else missing: value slots render "Unavailable",
        // valueless sections are omitted, gaps are listed, disclaimer stays mandatory.
        ResearchReportData.Entry empty = new ResearchReportData.Entry(
                "ZZZZ", "ZZZZ Corp.", null, null, null, null, null, null,
                0, 0, List.of(), null, null, null, null, null, null,
                "not-analyzed", null, null, null, null,
                0, 0, 0, 0, 0, null,
                List.of("quote unavailable for ZZZZ"));
        byte[] pdf = generator.generate(report(UUID.randomUUID(), List.of(empty), null, null, null));

        String text = textOf(pdf);
        assertThat(text).contains("ZZZZ Corp.");
        assertThat(text).contains("Unavailable");
        assertThat(text).contains("quote unavailable for ZZZZ");
        // Risk/news/interpretation sections are omitted when they have no data.
        assertThat(text).doesNotContain("Risk Analysis");
        assertThat(text).doesNotContain("AI INTERPRETATION");
        // Disclaimer is mandatory even for empty reports.
        assertThat(text).contains("DISCLAIMER");
    }

    @Test
    void unavailableSentimentShowsReason() throws Exception {
        ResearchReportData.Entry entry = new ResearchReportData.Entry(
                "AAPL", "AAPL Corp.", "150.25", "1.00", "0.67",
                null, null, null, 10, 0, List.of(),
                null, null, null, null, null, null,
                "unavailable", null, null, null, "NO_ARTICLES",
                0, 0, 0, 0, 0, "lexicon-v1",
                List.of("no news articles found for AAPL"));
        String text = textOf(generator.generate(report(UUID.randomUUID(), List.of(entry), null, null)));

        assertThat(text).contains("NO_ARTICLES");
    }

    @Test
    void longInterpretationFlowsAcrossMultiplePages() throws Exception {
        StringBuilder longText = new StringBuilder();
        for (int i = 0; i < 120; i++) {
            longText.append("Paragraph ").append(i)
                    .append(": the steady outlook continues with moderate risk and balanced coverage. ");
        }
        byte[] pdf = generator.generate(report(UUID.randomUUID(),
                List.of(fullEntry("AAPL")), longText.toString(), "Summary."));

        assertThat(pagesOf(pdf)).isGreaterThan(1);
        String text = textOf(pdf).replaceAll("\\s+", " ");
        assertThat(text).contains("Paragraph 0").contains("Paragraph 119");
        assertThat(text).contains("Page 2");
    }

    @Test
    void longHeadlineAndSpecialCharactersNeverBreakLayout() throws Exception {
        String nasty = "Täta Mötors — Münchener “Sonder-Edition” breaks records … ₹100 target?";
        ResearchReportData.Entry entry = new ResearchReportData.Entry(
                "TATA", nasty, "987.65", "-12.30", "-1.23",
                "Automobiles & Parts", "3450000000000", "9.8",
                15, 1, List.of(nasty + " " + nasty + " " + nasty),
                null, null, null, null, null, null,
                "not-analyzed", null, null, null, null,
                0, 0, 0, 0, 0, null, List.of());
        String text = textOf(generator.generate(report(UUID.randomUUID(), List.of(entry), null, null)));

        // Phase 17: Unicode fonts render everything verbatim — Latin-1 survives,
        // em-dashes/quotes/rupee are NO LONGER mapped or degraded (see
        // unicodeHeadlinesRenderVerbatim); nothing throws.
        assertThat(text).contains("Täta Mötors — Münchener");
        assertThat(text).contains("₹100");
        assertThat(text).contains("987.65");
    }

    @Test
    void noSecretsLeakIntoOutput() throws Exception {
        String text = textOf(generator.generate(
                report(UUID.randomUUID(), List.of(fullEntry("AAPL")), "Plain prose.", "Plain summary.")));

        assertThat(text).doesNotContain("Authorization");
        assertThat(text).doesNotContain("api-key");
        assertThat(text).doesNotContain("API_KEY");
    }

    @Test
    void nullDataRejected() {
        assertThatThrownBy(() -> generator.generate(null))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void sanitizeKeepsLatinText() {
        assertThat(PdfReportGenerator.sanitize("Café naïve façade")).isEqualTo("Café naïve façade");
        assertThat(PdfReportGenerator.sanitize("a—b–c“d”")).isEqualTo("a-b-c\"d\"");
    }
}
